--Run SecurityDDL to initialise DB

USE DiscHavenDB
GO

DROP TABLE IF EXISTS [tblCustomer];
GO
CREATE TABLE tblCustomer
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	UserName NVARCHAR(50) NOT NULL UNIQUE,
	FirstName NVARCHAR(50) NOT NULL,	
	LastName NVARCHAR(50) NOT NULL,	
	PasswordHash BINARY(64) NOT NULL,	
	Salt UNIQUEIDENTIFIER NOT NULL,	
	Email NVARCHAR(MAX) NOT NULL,	
	PostalNumber NVARCHAR(40) NOT NULL,	
	PostalStreet NVARCHAR(100) NOT NULL,
	PostalSuburb NVARCHAR(100) NOT NULL,	
	PostalTown NVARCHAR(100) NOT NULL,	
	PostalState NVARCHAR(4) NOT NULL,	
	PostalCountry NVARCHAR(100) NOT NULL,
	ShippingNumber NVARCHAR(40),	
	ShippingStreet NVARCHAR(100),
	ShippingSuburb NVARCHAR(100),	
	ShippingTown NVARCHAR(100),	
	ShippingState NVARCHAR(4),	
	ShippingCountry NVARCHAR(100),
	PostalIsShipping BIT NOT NULL DEFAULT(1)
)
GO

DROP TABLE IF EXISTS [tblRole];
GO
CREATE TABLE tblRole
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(10) NOT NULL
)
GO

DROP TABLE IF EXISTS [tblStaff];
GO
CREATE TABLE tblStaff
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Username NVARCHAR(50) NOT NULL UNIQUE,
	FirstName NVARCHAR(50) NOT NULL,	
	LastName NVARCHAR(50) NOT NULL,	
	PasswordHash BINARY(64) NOT NULL,	
	Salt UNIQUEIDENTIFIER NOT NULL,	
	Email NVARCHAR(MAX) NOT NULL,
	DateDeactivated DATETIME NULL DEFAULT NULL,
	FKRoleID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblRole]([ID])
)
CREATE INDEX [FKRoleID] ON tblStaff([FKRoleID]);
GO

DROP TABLE IF EXISTS [tblSecretQA];
GO
CREATE TABLE tblSecretQA
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Question VARBINARY(256) NOT NULL,
	Answer BINARY(64) NOT NULL,
	Salt UNIQUEIDENTIFIER NOT NULL,
	FKCustomerID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblCustomer]([ID])
)
CREATE INDEX [FKCustomerID] ON tblSecretQA([FKCustomerID]);
GO

DROP TABLE IF EXISTS [tblCategory];
GO
CREATE TABLE tblCategory
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Category NVARCHAR(30) NOT NULL
)
GO

DROP TABLE IF EXISTS [tblWork];
GO
CREATE TABLE tblWork
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(100) UNIQUE NOT NULL,
	FKCategoryID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblCategory]([ID])
)
CREATE INDEX [FKCategoryID] ON tblWork([FKCategoryID]);
GO

DROP TABLE IF EXISTS [tblMediaType];
GO
CREATE TABLE tblMediaType
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	MediaType NVARCHAR(20) NOT NULL
)
GO

DROP TABLE IF EXISTS [tblStockLocation];
GO
CREATE TABLE tblStockLocation
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(20) UNIQUE NOT NULL
)
GO

DROP TABLE IF EXISTS [tblProduct];
GO
CREATE TABLE tblProduct
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL DEFAULT('No description available'),
	[Image] NVARCHAR(MAX) NOT NULL,
	RRP DECIMAL(19,2) NOT NULL,
	SpecialPrice DECIMAL(19,2),
	[Status] BIT NOT NULL,
	FKWorkID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblWork]([ID]),
	FKMediaTypeID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblMediaType]([ID])
)
CREATE INDEX [FKWorkID] ON tblProduct([FKWorkID]);
CREATE INDEX [FKMediaTypeID] ON tblProduct([FKMediaTypeID]);
GO

DROP TABLE IF EXISTS [tblStock];
GO
CREATE TABLE tblStock
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Stock INT NOT NULL,
	FKLocationID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblStockLocation]([ID]),
	FKProductID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblProduct]([ID])
)
GO

DROP TABLE IF EXISTS [tblCartItem];
GO
CREATE TABLE tblCartItem
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Quantity INT NOT NULL,
	FKProductID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblProduct]([ID]),
	FKCustomerID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblCustomer]([ID])
)
GO

DROP TABLE IF EXISTS [tblStatus];
GO
CREATE TABLE tblStatus
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	[Status] NVARCHAR(30) NOT NULL
)
GO

DROP TABLE IF EXISTS [tblOrder];
GO
CREATE TABLE tblOrder
(
	ID BIGINT PRIMARY KEY IDENTITY(17286, 1) NOT NULL,
	PurchaseDate DATE NOT NULL DEFAULT GETDATE(),
	GST DECIMAL(19,2) NOT NULL,
	FKStatusID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblStatus]([ID]),
	FKCustomerID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblCustomer]([ID])
)
CREATE INDEX [FKStatusID] ON tblOrder([FKStatusID]);
CREATE INDEX [FKCustomerID] ON tblOrder([FKCustomerID]);
GO

DROP TABLE IF EXISTS [tblItemStatus]
GO
CREATE TABLE tblItemStatus
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	ItemStatus NVARCHAR(MAX) NOT NULL
)
GO

DROP TABLE IF EXISTS [tblOrderItem];
GO
CREATE TABLE tblOrderItem
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	Quantity INT NOT NULL,
	SalePrice DECIMAL(19,2),
	[Description] NVARCHAR(MAX) NOT NULL,
	FKOrderID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblOrder]([ID]),
	FKProductID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblProduct]([ID]),
	FKItemStatusID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblItemStatus]([ID])
)
CREATE INDEX [FKOrderID] ON tblOrderItem([FKOrderID]);
CREATE INDEX [FKProductID] ON tblOrderItem([FKProductID]);
GO

DROP TABLE IF EXISTS [tblSearch];
GO
CREATE TABLE tblSearch
(
	ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	SearchTerm NVARCHAR(MAX),
	WorkID BIGINT,
	CategoryID BIGINT,
	DateSearched DATETIME NOT NULL DEFAULT GETDATE(),
	FKCustomerID BIGINT NOT NULL FOREIGN KEY REFERENCES [tblCustomer]([ID])
)
GO

DROP TABLE IF EXISTS [tblProperties];
GO
CREATE TABLE tblProperties
(
	ID BIGINT PRIMARY KEY NOT NULL DEFAULT 1 CHECK ([ID] = 1),
	GST DECIMAL(19,2) NOT NULL DEFAULT(10.00),
	SecretQAAmount INT NOT NULL DEFAULT(3),
	WareHouseStoreID BIGINT NOT NULL DEFAULT(3),
	RequiredQA INT NOT NULL DEFAULT(2)
)
GO